<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1758817737696' stop='1758817745514'>
    <name>TesteSuit</name>
    <title>TesteSuit</title>
    <test-cases>
        <test-case start='1758817737698' status='passed' stop='1758817739947'>
            <name>testing1</name>
            <title>testing1</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1758817739959' status='failed' stop='1758817745489'>
            <name>testing2</name>
            <title>testing2</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Timed out retrying after 4000ms: expected 'https://www.saucedemo.com/' to equal 'https://www.saucedemo.com/inventory.html'</message>
                <stack-trace>AssertionError: Timed out retrying after 4000ms: expected 'https://www.saucedemo.com/' to equal 'https://www.saucedemo.com/inventory.html'
                    at Context.eval (webpack://cypress/./cypress/e2e/examples.cy.js:37:17)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>